/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiVideoGeneratorRouteImport } from './routes/ai-video-generator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CharacterSwapRouteImport } from './routes/character-swap'
import { Route as ElevenLabsRouteImport } from './routes/eleven-labs'
import { Route as ElevenLabsMusicRouteImport } from './routes/eleven-labs-music'
import { Route as ImageToVideoRouteImport } from './routes/image-to-video'
import { Route as MeshyIaRouteImport } from './routes/meshy-ia'
import { Route as MultiSceneRouteImport } from './routes/multi-scene'
import { Route as Wan22RouteImport } from './routes/wan-2-2'
import { Route as ApiPublicVideoProxyRouteImport } from './routes/api/public/video-proxy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVideoGeneratorRoute = AiVideoGeneratorRouteImport.update({
  id: '/ai-video-generator',
  path: '/ai-video-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterSwapRoute = CharacterSwapRouteImport.update({
  id: '/character-swap',
  path: '/character-swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevenLabsRoute = ElevenLabsRouteImport.update({
  id: '/eleven-labs',
  path: '/eleven-labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevenLabsMusicRoute = ElevenLabsMusicRouteImport.update({
  id: '/eleven-labs-music',
  path: '/eleven-labs-music',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToVideoRoute = ImageToVideoRouteImport.update({
  id: '/image-to-video',
  path: '/image-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshyIaRoute = MeshyIaRouteImport.update({
  id: '/meshy-ia',
  path: '/meshy-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiSceneRoute = MultiSceneRouteImport.update({
  id: '/multi-scene',
  path: '/multi-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const Wan22Route = Wan22RouteImport.update({
  id: '/wan-2-2',
  path: '/wan-2-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoProxyRoute = ApiPublicVideoProxyRouteImport.update({
  id: '/api/public/video-proxy',
  path: '/api/public/video-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/auth': typeof AuthRoute
  '/character-swap': typeof CharacterSwapRoute
  '/eleven-labs': typeof ElevenLabsRoute
  '/eleven-labs-music': typeof ElevenLabsMusicRoute
  '/image-to-video': typeof ImageToVideoRoute
  '/meshy-ia': typeof MeshyIaRoute
  '/multi-scene': typeof MultiSceneRoute
  '/wan-2-2': typeof Wan22Route
  '/api/public/video-proxy': typeof ApiPublicVideoProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/auth': typeof AuthRoute
  '/character-swap': typeof CharacterSwapRoute
  '/eleven-labs': typeof ElevenLabsRoute
  '/eleven-labs-music': typeof ElevenLabsMusicRoute
  '/image-to-video': typeof ImageToVideoRoute
  '/meshy-ia': typeof MeshyIaRoute
  '/multi-scene': typeof MultiSceneRoute
  '/wan-2-2': typeof Wan22Route
  '/api/public/video-proxy': typeof ApiPublicVideoProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/auth': typeof AuthRoute
  '/character-swap': typeof CharacterSwapRoute
  '/eleven-labs': typeof ElevenLabsRoute
  '/eleven-labs-music': typeof ElevenLabsMusicRoute
  '/image-to-video': typeof ImageToVideoRoute
  '/meshy-ia': typeof MeshyIaRoute
  '/multi-scene': typeof MultiSceneRoute
  '/wan-2-2': typeof Wan22Route
  '/api/public/video-proxy': typeof ApiPublicVideoProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-video-generator'
    | '/auth'
    | '/character-swap'
    | '/eleven-labs'
    | '/eleven-labs-music'
    | '/image-to-video'
    | '/meshy-ia'
    | '/multi-scene'
    | '/wan-2-2'
    | '/api/public/video-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-video-generator'
    | '/auth'
    | '/character-swap'
    | '/eleven-labs'
    | '/eleven-labs-music'
    | '/image-to-video'
    | '/meshy-ia'
    | '/multi-scene'
    | '/wan-2-2'
    | '/api/public/video-proxy'
  id:
    | '__root__'
    | '/'
    | '/ai-video-generator'
    | '/auth'
    | '/character-swap'
    | '/eleven-labs'
    | '/eleven-labs-music'
    | '/image-to-video'
    | '/meshy-ia'
    | '/multi-scene'
    | '/wan-2-2'
    | '/api/public/video-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiVideoGeneratorRoute: typeof AiVideoGeneratorRoute
  AuthRoute: typeof AuthRoute
  CharacterSwapRoute: typeof CharacterSwapRoute
  ElevenLabsRoute: typeof ElevenLabsRoute
  ElevenLabsMusicRoute: typeof ElevenLabsMusicRoute
  ImageToVideoRoute: typeof ImageToVideoRoute
  MeshyIaRoute: typeof MeshyIaRoute
  MultiSceneRoute: typeof MultiSceneRoute
  Wan22Route: typeof Wan22Route
  ApiPublicVideoProxyRoute: typeof ApiPublicVideoProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-video-generator': {
      id: '/ai-video-generator'
      path: '/ai-video-generator'
      fullPath: '/ai-video-generator'
      preLoaderRoute: typeof AiVideoGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-swap': {
      id: '/character-swap'
      path: '/character-swap'
      fullPath: '/character-swap'
      preLoaderRoute: typeof CharacterSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleven-labs': {
      id: '/eleven-labs'
      path: '/eleven-labs'
      fullPath: '/eleven-labs'
      preLoaderRoute: typeof ElevenLabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleven-labs-music': {
      id: '/eleven-labs-music'
      path: '/eleven-labs-music'
      fullPath: '/eleven-labs-music'
      preLoaderRoute: typeof ElevenLabsMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-video': {
      id: '/image-to-video'
      path: '/image-to-video'
      fullPath: '/image-to-video'
      preLoaderRoute: typeof ImageToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meshy-ia': {
      id: '/meshy-ia'
      path: '/meshy-ia'
      fullPath: '/meshy-ia'
      preLoaderRoute: typeof MeshyIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-scene': {
      id: '/multi-scene'
      path: '/multi-scene'
      fullPath: '/multi-scene'
      preLoaderRoute: typeof MultiSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wan-2-2': {
      id: '/wan-2-2'
      path: '/wan-2-2'
      fullPath: '/wan-2-2'
      preLoaderRoute: typeof Wan22RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-proxy': {
      id: '/api/public/video-proxy'
      path: '/api/public/video-proxy'
      fullPath: '/api/public/video-proxy'
      preLoaderRoute: typeof ApiPublicVideoProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiVideoGeneratorRoute: AiVideoGeneratorRoute,
  AuthRoute: AuthRoute,
  CharacterSwapRoute: CharacterSwapRoute,
  ElevenLabsRoute: ElevenLabsRoute,
  ElevenLabsMusicRoute: ElevenLabsMusicRoute,
  ImageToVideoRoute: ImageToVideoRoute,
  MeshyIaRoute: MeshyIaRoute,
  MultiSceneRoute: MultiSceneRoute,
  Wan22Route: Wan22Route,
  ApiPublicVideoProxyRoute: ApiPublicVideoProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
